" Vim compiled with python

" Plugin manager (change path below to match the current vim installation)
call plug#begin('C:\Program Files (x86)\complete-x86\plugged')

Plug 'ervandew/supertab'

call plug#end()


" User specific 
syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set ai
set number
set hlsearch
set ruler

colorscheme default

inoremap jk <ESC>

" jump between buffers
nnoremap <s-h> :bprevious<cr> 
nnoremap <s-l> :bnext<cr>
 
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

set nobackup nowritebackup noswapfile       

set background=dark

if has ('unix')
   language messages C
else 
   language messages English_United States
   set langmenu=en_US.UTF-8
endif

hi Normal ctermfg=white guibg=black
hi Constant ctermfg=red guibg=black
hi Type ctermfg=darkgreen guibg=black
hi Comment ctermfg=darkgrey guibg=black
hi cCustomFunc ctermfg=darkcyan guibg=black
hi cCustomClass ctermfg=darkcyan guibg=black

