syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab
set ai
set number
set hlsearch
set ruler

colorscheme default

inoremap jk <ESC>
xnoremap jk <ESC>
nnoremap <s-h> :bprevious<cr>
nnoremap <s-l> :bnext<cr>
 
set enc=utf-8
set fenc=utf-8
set termencoding=utf-8

set nobackup nowritebackup noswapfile

set background=dark

if has ('unix')
   language messages C
else 
   language messages English_United States
   set langmenu=en_US.UTF-8
endif

highlight Normal ctermfg=white guibg=black
highlight Constant ctermfg=red guibg=black
highlight Type ctermfg=darkgreen guibg=black
highlight Comment ctermfg=darkgrey guibg=black
hi cCustomFunc ctermfg=darkcyan guibg=black
hi cCustomClass ctermfg=darkcyan guibg=black
